### ISSUE TITLE
ClerverTapSDK/ClevertTap.h not found

### ISSUE THREAD

**Issue by sanhue0302** [CleverTap/clevertap-segment-ios#10]
I installed using 

>pod "Segment-CleverTap"

when I build, it shows "ClerverTapSDK/ClevertTap.h not found" at SEGClevertapIntegration.m

I think it shuold fix as #import <CleverTap-iOS-SDK/CleverTap.h>

**Comment by Aditi3** [comment]
Hey @sanhue0302 

Have you tried including `use_frameworks!` in the pod file and then build your project?

CleverTapSDK is a dynamic framework, by specifying `use_frameworks!` you can make CocoaPods integrate into your project via frameworks instead of static libraries.

To help you better, I recommend you to check out our Demo Applications:
https://github.com/CleverTap/clevertap-segment-ios/tree/master/ExampleSwift
https://github.com/CleverTap/clevertap-segment-ios/tree/master/Example

Hope this helps :)

**Comment by sanhue0302** [comment]
I am using static library in my project. Because some of our pod's only supports static library.
I use your source files and edit the import line in my project now.
thx.

**Comment by Aditi3** [comment]
Hi @sanhue0302 

We have made the required changes in the header format for the projects/ applications which can't include `use_frameworks!` in their pod file.
[Here]( https://github.com/CleverTap/clevertap-segment-ios/releases/tag/1.1.5) is the link to the release that comes with the fix.

Hope this helps :)
