### ISSUE TITLE
<CleverTapSDK/CleverTap.h> file not found

### ISSUE THREAD

**Issue by hbursk** [CleverTap/clevertap-segment-ios#3]
The CleverTapSDK for iOS has it's public headers installed under Pods/Headers/Public/CleverTap-iOS-SDK so the reference to <CleverTapSDK/CleverTap.h> on line 2 of SEGCleverTapIntegration.m can't be resolved. Manually editing the file to:

#import <CleverTap-iOS-SDK/CleverTap.h>

fixes the issue.

**Comment by Aditi3** [comment]
Hey @hbursk 

Seems like you have not included `use_frameworks!` in your Podfile.   

CleverTapSDK is now a dynamic framework, by specifying `use_frameworks!`you can make CocoaPods integrate to your project via frameworks instead of static libraries.

The following code snippet will be useful for you:

```
target 'YOUR_TARGET_NAME' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for YOUR_TARGET_NAME
  pod "Segment-CleverTap"
end
```
